@startuml
class User{
+Int32 Id
+String Name
+String Email
+String Password
}

class Accounts{
+Int32 Id
+String Login
+String Password
+String Email
}

class Books{
+Int32 Id
+String Title
+String Description
+String Author
+DateTime DateTime
}

@enduml