@startuml
class User{
+Int32 Id
+String Name
+String Email
+String Password
+Accounts accounts
}

User "1" --- "1" Accounts
class Accounts{
+Int32 Id
+String Login
+String Password
+String Email
+List`1 Books
}

Accounts "1" --- "M" Books
class Books{
+Int32 Id
+String Title
+String Description
+String Author
+DateTime DateTime
+List`1 Accounts
}

Books "1" --- "M" Accounts
@enduml